<?php
 return array (
  0 => 'Automatic Transfer Rules',
  1 => 'autoreply1',
  2 => 'AutoTransferSystem',
  3 => 'auto_transfers',
  4 => 'auto_transferss',
  5 => 'Banner System',
  6 => 'banners',
  7 => 'brand',
  8 => 'clientScript',
  9 => 'communication',
  10 => 'environment',
  11 => 'l10n',
  12 => 'landing',
  13 => 'niche',
  14 => 'permissions',
  15 => 'RabbitMQ',
  16 => 'search',
  17 => 'Site Group',
  18 => 'trackingCode',
  19 => 'urlManager',
  20 => 'urlManagerRestore',
  21 => 'CrmTechnical',
  22 => 'CrmBusinessRules',
);
?>