<?php
 return array (
    'Automatic Transfer Rules',
    'autoreply',
    'AutoTransferSystem',
    'auto_transfers',
    'auto_transferss',
    'Banner System',
    'banners',
    'brand',
    'clientScript',
    'communication',
    'environment',
    'l10n',
    'landing',
    'niche',
    'permissions',
    'RabbitMQ',
    'search',
    'Site Group',
    'trackingCode',
    'urlManager',
    'urlManagerRestore',
    'CrmTechnical',
    'CrmBusinessRules',
    'Automatic Transfer Rules',
);
?>